dist: trusty
rvm: 2.4.1
cache:
  bundler: true
  directories:
  - vendor/bundle
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - ca-certificates
stages:
  - name: Test
    if: sender != svenfuchs AND sender != imgbot[bot]
  - name: imgbot
    if: sender IN (svenfuchs, imgbot[bot])
  - name: Run build
    if: type IN (push, cron) AND (branch = master OR tag IS present)
jobs:
  include:
    - &test-baseline
      stage: Test
      script:
        bundle exec rake
      
    - <<: *test-baseline
      script:
        bundle exec rake proof_external
      if: type IN (pull_request, cron) OR (type = push AND branch = master)
    
    - stage: imgbot
      script:
        bundle exec rake verify
    
    - stage: Run build
      sudo: true
      env: 
        NEXT_BUILD_TAG=latest
      script:
      - if [ "$TRAVIS_TAG" != "" ]; then 
          NEXT_BUILD_TAG=`date +"%m-%d-%Y"`;
        fi
      - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then 
          NEXT_BUILD_TAG=`date +"%m-%d-%Y"`;
        fi
      - echo $NEXT_BUILD_TAG
      - bundle exec rake assets:precompile
      deploy:
      - provider: heroku
        skip-cleanup: true
        api_key: $HEROKU_KEY
        on:
          all_branches: true # <== new!
          condition: $NEXT_BUILD_TAG != "latest"
      # - provider: pages
        # skip-cleanup: true
        # github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        # fqdn: beta.acceptbitco.in
        # keep-history: true
        # repo: bigearth/spec.consortium.cash
        # target_branch: gh-pages
        # on:
          # all_branches: true # <== new!
  allow_failures:
    - stage: Test
      script:
        bundle exec rake proof_external
      if: type IN (pull_request, cron) OR (type = push AND branch = master)
notifications:
  webhooks: 
    urls: https://www.travisbuddy.com/
    on_failure: always
    on_success: never
